### ISSUE TITLE
Link to demo account

### ISSUE THREAD

**Issue by balza** [keycloak/keycloak-documentation#1308]
### Describe the bug

At https://www.keycloak.org/docs/latest/getting_started/index.html#logging-into-the-account-console the link http://localhost:8080/auth/realms/demo/account 
could be wrong. The right one should be 
http://localhost:8080/realms/demo/account/

### Version

15.0.2

**Comment by stianst** [comment]
The documentation has been moved to [the main Keycloak repository](https://github.com/keycloak/keycloak/tree/main/docs/documentation).

Closing this issue as its been around for a long time without any updates. If still relevant please open a new issue in [the main repository](https://github.com/keycloak/keycloak/issues).
