### ISSUE TITLE
Add more / clearer documentation on AIAs

### ISSUE THREAD

**Issue by damnedOperator** [keycloak/keycloak-documentation#1320]
### Description

I am requesting an enhancement (a creation) of official Keycloak documentation for Application Initiated Actions, which go into more technical detail than just the design document. 

It is a small addition to the docs, but I am sure this will save a load of people which want to implement AIA in their apps a lot of time that is currently used in experimenting around to get it to work.

### Motivation

Documentation on Application Initiated Actions right now seems to be limited to [the design document](https://github.com/keycloak/keycloak-community/blob/master/design/application-initiated-actions.md), some (for not React developers) [confusing react frontend code](https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/keycloak.v2/account/src/app/content/signingin-page/SigningInPage.tsx#L228-L249) and [a google groups entry pointing to both the latter](https://groups.google.com/g/keycloak-user/c/sh67H2EvHDg).

It is okay and all to have a feature that ["pretty much turned out as designed"](https://groups.google.com/g/keycloak-user/c/sh67H2EvHDg#:~:text=pretty%20much%20turned%20out%20as%20designed) but there is still a need for improvement on this documentation.

### Details

My Proposals for this documentation are:
- What are kc_action Keywords like UPDATE_PASSWORD, UPDATE_PROFILE, etc.?
- Explicitly mention the need to have kc_action value as ALL CAPS (otherwise resulting in a confusing error message)
- Which Endpoint and GET Parameters are required (Parallel to the design document)?
- When should AIAs be used?
- Is there (if any) implementation into the Client SDKs?

**Comment by MPParsley** [comment]
(how) is it possible to backport any of the React 'AIACommand' to an .ftl theme?

**Comment by stianst** [comment]
The documentation has been moved to [the main Keycloak repository](https://github.com/keycloak/keycloak/tree/main/docs/documentation).

Closing this issue as its been around for a long time without any updates. If still relevant please open a new issue in [the main repository](https://github.com/keycloak/keycloak/issues).
