### ISSUE TITLE
KeyCloak Operator uses DNS_PING, not JDBC_PING.

### ISSUE THREAD

**Issue by tmurakam** [keycloak/keycloak-documentation#1351]
### Describe the bug

server_installation/topics/operator/keycloak-cr.adoc says:

> keycloak-discovery Service - Performs JDBC_PING discovery

But it seems that the operator implementation uses DNS_PING, not JDBC_PING.

Source code: https://github.com/keycloak/keycloak-operator/blob/main/pkg/model/keycloak_deployment.go

### Version

16.1.0

**Comment by stianst** [comment]
Server installation guide is no longer maintained for new distribution of Quarkus. Please refer to the updated guides https://www.keycloak.org/guides
