### ISSUE TITLE
JavaScript providers - Create a JAR with the scripts to deploy - missing services directory

### ISSUE THREAD

**Issue by BlackKerio** [keycloak/keycloak-documentation#1357]
### Describe the bug

when creating the script as instructed ...,
META-INF/keycloak-scripts.json
my-script-authenticator.js
my-script-policy.js
my-script-mapper.js

after installation and the next time the user logs in, there is an error was reported that in the services directory was unable to find factory for AuthenticatorFactory.

### Version

15.1.1

### Expected behavior

In the documentation for creating a script using javascript, the services directory is not specified

### Actual behavior

Error message without services directory :
[org.keycloak.services] (default task-4) KC-SERVICES0013: Failed authentication: java.lang.RuntimeException: Unable to find factory for AuthenticatorFactory: script-my-script-authenticator.js did you forget to declare it in a META-INF/services file?

### How to Reproduce?

the error occurs only when you have already installed a JAVA module (also a .jar file) in the directory deployments

### Anything else?

it's probably a system error, but I think it's necessary to mention a possible conflict in the documentation

**Comment by stianst** [comment]
Closing as out of date. Please try with the latest documentation and release.
