### ISSUE TITLE
JavaDoc(Documentation for Java API)  link broken?

### ISSUE THREAD

**Issue by zedbeit** [keycloak/keycloak-documentation#1361]
### Describe the bug

Page not found.
![Screenshot from 2022-01-17 13-45-06](https://user-images.githubusercontent.com/57130151/149772475-c312bfb0-c02d-4653-93fb-f6308adb4aa5.png)

### Version

null

**Comment by ahus1** [comment]
This has been fixed in the meantime, see https://www.keycloak.org/docs-api/16.1/javadocs/index.html

![image](https://user-images.githubusercontent.com/3957921/175604389-61fa420b-b296-4289-8083-5673607f54ac.png)
