### ISSUE TITLE
Documentation for proxy is incorrect since the upgrade to WildFly 23

### ISSUE THREAD

**Issue by monzonj** [keycloak/keycloak-documentation#1364]
### Describe the bug

The documentation here https://www.keycloak.org/docs/latest/server_installation/#_proxymappings says:

```
# Configure the proxy-mappings
/subsystem=keycloak-server/spi=connectionsHttpClient/provider=default:write-attribute(name=properties.proxy-mappings,value=[".*\\.(google|googleapis)\\.com;http://www-proxy.acme.com:8080",".*\\.acme\\.com;NO_PROXY",".*;http://fallback:8080"])
```

But in version 25, value is no longer an array, but a string. This works:

```
# Configure the proxy-mappings
/subsystem=keycloak-server/spi=connectionsHttpClient/provider=default:write-attribute(name=properties.proxy-mappings,value="[\".*\\.(google|googleapis)\\.com;http://www-proxy.acme.com:8080\",\".*\\.acme\\.com;NO_PROXY\",\".*;http://fallback:8080\"]")
```

Notice value is now a string and the quotes are escaped.

### Version

16.1.0

### Expected behavior

Following the proxy configuration documentation should work. instead we get a wildfly error

### Actual behavior

We get an error from Wildfly if we follow the documentation

### How to Reproduce?

Just follow the documentation and install a proxy

**Comment by stianst** [comment]
Server installation guide was removed, please see updated server guides for the new distribution at https://www.keycloak.org/guides
