### ISSUE TITLE
Migrate scripts fail because of the upgrade to Wildfly 25

### ISSUE THREAD

**Issue by monzonj** [keycloak/keycloak-documentation#1365]
### Describe the bug

Script such as `migrate-standalone-ha.cli` fail to run in Keycloak 16.1.0 because it tries to update parts of the configuration file that are no longer present in wildfly

workaround: if you are upgrading from version 15, remove everything and only keep the changes from 15 to 16

### Version

16.1.0

### Expected behavior

Running the upgrade scrpits (e.g. migrate-standalone-ha.cli) should work as prescribed in the documentation

### Actual behavior

the scripts (e.g. migrate-standalone-ha.cli) fail to run

### How to Reproduce?

Just follow the upgrade documentation and run any of the upgrade scripts in version 16.1.0

**Comment by stianst** [comment]
WildFly distribution is no longer supported, and there are no migration scripts like this in the new Quarkus dist
