### ISSUE TITLE
Admin REST API doc is missing `admin` in base path

### ISSUE THREAD

**Issue by zedbeit** [keycloak/keycloak-documentation#1366]
### Describe the bug

Was getting "HTTP 404 Not Found" error while trying to invoke any of the admin REST endpoints, but it worked after i added "admin" to the base path. e.g `http://localhost:9000/admin/realms/{realm}/users`

### Version

null

**Comment by stianst** [comment]
Docs show that admin should be included:

![image](https://user-images.githubusercontent.com/2271511/226293523-0026b938-cca7-42bb-bc75-49861542ecdc.png)
