### ISSUE TITLE
Wrong documentation about automatic update password action

### ISSUE THREAD

**Issue by nerrehmit** [keycloak/keycloak-documentation#1371]
### Describe the bug

The documentation for version 16.1 of Keycloak mentions that a "update password action" will be set for every user in the affected realm when configuring a new password policy.

> After saving the policy, Keycloak enforces the policy for new users and sets an Update Password action for existing users to ensure they change their password the next time they log in.
https://www.keycloak.org/docs/latest/server_admin/#_password-policies

Compared to the old text in the v 15.0.2 documentation.
https://www.keycloak.org/docs/15.0/server_admin/#_password-policies

> After saving your policy, user registration and the Update Password required action will enforce your new policy. An example of a user failing the policy check:
> If the password policy is updated, an Update Password action must be set for every user. An automatic trigger is scheduled as a future enhancement.

the wording was changed considerably in this commit: https://github.com/keycloak/keycloak-documentation/commit/ba807279bdf92fcdd25b261d9dbf6857876f2115#diff-557f09ffc0aaabd2c33c1d43b354bb99c05a573c4ada6f1af6a0f7a534d4c2ccL17-L24

With my installation of Keycloak 16.1.0 I cannot observe the new functionality and the release notes do not mention such a feature. Is this a documentation error or should this work and I'd have to open an issue in the Keycloak code repository?

### Version

16.1.0

**Comment by stianst** [comment]
The documentation has been moved to [the main Keycloak repository](https://github.com/keycloak/keycloak/tree/main/docs/documentation).

Closing this issue as its been around for a long time without any updates. If still relevant please open a new issue in [the main repository](https://github.com/keycloak/keycloak/issues).
