### ISSUE TITLE
Deploying themes through jar documented incorrectly

### ISSUE THREAD

**Issue by Tillaert** [keycloak/keycloak-documentation#1383]
### Describe the bug

[Themes deployment documentation](https://github.com/keycloak/keycloak-documentation/blob/main/server_development/topics/themes.adoc#deploying-themes)

Mentions that theme files should be in the `themes` folder, should be `theme`.

### Version

16.1.1

**Comment by stianst** [comment]
In more recent versions the folder is `themes`.
