### ISSUE TITLE
Missing REST API Documentations

### ISSUE THREAD

**Issue by FreckTech** [keycloak/keycloak-documentation#1398]
### Description

Too many Rest API endpoints are not documented, and only way to know about them is through the inspect window of the browser at the "Administrator Console" page

### Motivation

To avoid unintentional bugs due to miss use of an Endpoint

### Details

I have been using Keycloak REST API for awhile now, and I always find missing endpoints in the [REST API Documentations](https://www.keycloak.org/docs-api/16.1/rest-api/index.html), which I can get only by inspecting the window of the browser when I'm in the "Administrator Console" page as shown in the following image example:

![Issue1](https://user-images.githubusercontent.com/32916450/152573677-f36ec807-5f8a-47ff-b5d2-8d878c7fd890.PNG)
<br><br><br>

This actually causes a lot of issues, like what parameters affects a specific endpoint differently.

For example, I made a function to get all the resources of a specific client so I used this `{your-keycloak-server}/admin/realms/{realm}/clients/{id}/authz/resource-server/resource`
and it turned out that the endpoint will max out the response to 100 records by default!
So, in that case I thought of settings the "max" parameter in the url to very big number like this `{your-keycloak-server}/admin/realms/{realm}/clients/{id}/authz/resource-server/resource?max=9999999`, but after multiple attempts to resolve that with better solution, I found that you could disable the max only if you set it to -1 like this `{your-keycloak-server}/admin/realms/{realm}/clients/{id}/authz/resource-server/resource?max=-1`

Hence, I hope someone shed some light, if there is a reason these endpoints are not documented, or if they just missed. If they are missed, then we should start adding them to the documentations. What do you think?

**Comment by stianst** [comment]
Closing this as it's too vague and broad, and will just end up lingering without any action.

**Comment by FreckTech** [comment]
@stianst Should I open an issue for each endpoint I found that is not documented in the [REST API Documentations](https://www.keycloak.org/docs-api/16.1/rest-api/index.html)?
I can initiate the action by adding these missing endpoint documentations I could find and make a pull request for it.
Your thoughts please.

**Comment by stianst** [comment]
If it's only authz services related things that are missing (and quick look at docs it seems those are completely missing for some reason), then a single umbrella issue that authz services endpoints like resources/policies/etc are missing would be sufficient. However, please make it specific that endpoints x,y,z are missing, as that makes it a lot easier for us to triage and take action on.

**Comment by FreckTech** [comment]
@stianst 
https://github.com/keycloak/keycloak/issues/19143
