### ISSUE TITLE
Missing/misleading documentation for kubernetes cache config

### ISSUE THREAD

**Issue by vanrar68** [keycloak/keycloak-documentation#1416]
### Describe the bug

Keycloak 17.0.0 "Configuring distributed cache" guide states that:

```
The following table shows transport stacks that are available without any further configuration than using the --cache-stack build option:
- tcp
- udp
- kubernetes
```

Actualy the 'kubernetes' cache stack requires the Java property `jgroups.dns.query` to be set. This property should be set to a Kubernetes keycloak headless service FQDN.
This property can be added to the JAVA_OPTS env var by adding -Djgroups.dns.query=[headless-service FQDN]

### Version

17.0.0

### Expected behavior

Include required property documentation

### Actual behavior

Misses required property documentation

**Comment by DavidHaltinner** [comment]
I am wondering if JAVA_OPTS_APPEND might be a better option at least for the documentation, as that does not overwrite the default options passed to java. Some users may wish to override the default java options, but I am guessing most would prefer to use JAVA_OPTS_APPEND

**Comment by vanrar68** [comment]
The cache guide is part of the keycloak repository. I submitted [PR #10425](https://github.com/keycloak/keycloak/pull/10425) over there

**Comment by matheushent** [comment]
if the PR is merged then I gues we can close this issue, can't we? It was indeed very helpful for me
