### ISSUE TITLE
OIDC GOOGLE prompt=select_account

### ISSUE THREAD

**Issue by SylvainAssemat** [keycloak/keycloak-documentation#1418]
### Description

Hi

I just read the documentation (17.0.0) and i saw that the **select_account** parameter is not available for the prompt option.

From : [https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)

_select_account
The Authorization Server SHOULD prompt the End-User to select a user account. This enables an End-User who has multiple accounts at the Authorization Server to select amongst the multiple accounts that they might have current sessions for. If it cannot obtain an account selection choice made by the End-User, it MUST return an error, typically account_selection_required._

May you provide this feature in the future ?

Thanks

### Motivation

This could be useful to switch using multiple accounts (personal, pro, ...)

**Comment by stianst** [comment]
If still relevant please open an issue in https://github.com/keycloak/keycloak/issues
