### ISSUE TITLE
Add documentation for recovery codes

### ISSUE THREAD

**Issue by stelewis-redhat** [keycloak/keycloak-documentation#1433]
### Description

Recovery codes is a new preview features in upstream Keycloak that allows a user to log into their account with a recovery code in case they lose access to other 2FA login methods.

**Comment by stelewis-redhat** [comment]
https://github.com/keycloak/keycloak-documentation/pull/1429 is the PR.

**Comment by stelewis-redhat** [comment]
team/rh-iam is tracking this in RH-SSO.

**Comment by mposolda** [comment]
This is already merged in keycloak "main" branch: https://github.com/keycloak/keycloak-documentation/pull/1429
