### ISSUE TITLE
Account Console chapter

### ISSUE THREAD

**Issue by andymunro** [keycloak/keycloak-documentation#1494]
### Description

Update this Server Administration Guide chapter for Account Console changes

**Comment by agagancarczyk** [comment]
hi @andymunro I can take a look at this issue, but could you please confirm what chapter needs to be updated? Is it https://www.keycloak.org/docs/latest/server_admin/#keycloak-features-and-concepts ?Thanks

**Comment by andymunro** [comment]
Sure, @agagancarczyk.  We need to check if the Account Console is up-to-date, which is actually an independent exercise of updating the Server Administration Guide for the new Admin Console.
Anyway, here is the chapter with that content; https://raw.githubusercontent.com/keycloak/keycloak-documentation/main/server_admin/topics/account.adoc
