### ISSUE TITLE
Using token exchange chapter

### ISSUE THREAD

**Issue by andymunro** [keycloak/keycloak-documentation#1495]
### Description

Update this Securing Apps and Services Guide chapter for the new Admin Console

**Comment by agagancarczyk** [comment]
hi @andymunro Jon asked me to take this over from him. Is this the correct content that needs updating? https://www.keycloak.org/docs/latest/securing_apps/ Thanks

**Comment by andymunro** [comment]
Yes, it's the last chapter of this guide that needs updates.
