### ISSUE TITLE
Outdated documentation for features

### ISSUE THREAD

**Issue by blacklight** [keycloak/keycloak-documentation#1527]
### Describe the bug

The [documentation for features](https://github.com/keycloak/keycloak-documentation/blob/main/server_installation/topics/profiles.adoc) reports the `standalone.sh` script (as well as a `standalone/configuration` directory). None of these is available, at least not in the most recent Keycloak version. Maybe it should be updated to `kc.sh`?

### Version

18.0.0

**Comment by stianst** [comment]
Here's the updated documentation for the Quarkus dist https://www.keycloak.org/server/features
