### ISSUE TITLE
Truststore documentation is outdated (?)

### ISSUE THREAD

**Issue by nzsb** [keycloak/keycloak-documentation#1553]
### Description

I think it should be noted in documentation, that for integrating with external identity providers (with SAML with https, for instance), there is no need to configured the truststore, because it can be configured with dashboard.
Also, I believe that standalone.xml and co. only existed for old versions using JBoss, for Keycloak 18.0.0 environment variables KC_HTTPS_TRUST_STORE_FILE and co. can be used.
At least this was very misleading for me, but I am a newbie.

Reference:
https://www.keycloak.org/docs/latest/server_installation/index.html#_truststore

**Comment by stianst** [comment]
Server installation guide was specifically for the WildFly distribution, please see updated guides for details on the Quarkus distribution
