### ISSUE TITLE
Update Account Console screens in Authorization Services guide

### ISSUE THREAD

**Issue by andymunro** [keycloak/keycloak-documentation#1610]
### Description

In the Authorization Services Guide, Authorization services > User-managed access > Managing access to users resources section, there are two screen shots to the old account console.

Also, the screens should be preceded by the following step to switch from the Admin Console to the Account Console.

. Click the user name a the top right of the Admin Console and select *Manage Account*.
+
The Account Console appears.

This PR can be targeted to upstream/main.  It can be done with NO conditional codes.

**Comment by edewit** [comment]
This is showing the account console, that didn't change right we only changed the admin console

**Comment by edewit** [comment]
also the switch ` Click the user name a the top right of the Admin Console and select Manage Account.` is still the same

**Comment by andymunro** [comment]
Thanks, @edewit.  Yes, this issue is not related to the Admin Console update.  The account console, however, has changed.  QE points out that screens are out of date.
Concerning the instruction "select Manage Account," that has not changed. That's true but that step is missing from the existing documentation.
