### ISSUE TITLE
Add OCP4 specific templates to Get Started guide

### ISSUE THREAD

**Issue by Pepo48** [keycloak/keycloak-documentation#1614]
### Description

In our OCP Get Started guide the OCP4 specific templates are missing. Therefore  {project_templates_version}-ocp4-x509-postgresql-persistent.json and {project_templates_version}-ocp4-x509-https.json should be mentioned at least during updating the core template set[1].

[1] https://github.com/keycloak/keycloak-documentation/blame/main/openshift/topics/get_started.adoc#L47L52

**Comment by stianst** [comment]
OpenShift documentation is no longer maintained, please see updated guides for the new distribution
