### ISSUE TITLE
Missing map-storage and dynamic-scopes feature category

### ISSUE THREAD

**Issue by MansurAliKoroglu** [keycloak/keycloak-documentation#1645]
### Description

In https://www.keycloak.org/server/features page features are listed with categories like `Supported features` or `Disabled by default` etc.

`map-storage` and `dynamic-scopes` can be enabled or disabled with `--features` and `--features-disabled` command but they are not categorized under any title in the documentation page. Are they Preview features or deprecated or no more valid? Should be described in that page.

### Motivation

Better documentation.

**Comment by stianst** [comment]
The features you mention are experimental features, and as such are not listed in the documentation
