### ISSUE TITLE
REST API documentation not working for v19

### ISSUE THREAD

**Issue by TheSlimvReal** [keycloak/keycloak-documentation#1648]
### Describe the bug

Clicking the link to the [Administration REST API](https://www.keycloak.org/docs-api/19.0/rest-api/index.html) returns a 404 for the latest version (v19)

### Version

19.0.0

### Expected behavior

The current documentation of the REST API should be shown

### Actual behavior

The page is not found (404)

### How to Reproduce?

Got to [https://www.keycloak.org/documentation](https://www.keycloak.org/documentation) and click on Administration REST API at the bottom of the page.

**Comment by alia5gar** [comment]
You can find the documentation at 
https://www.keycloak.org/docs-api/19.0.1/rest-api/index.html

**Comment by TheSlimvReal** [comment]
Looks like it has been solved now
