### ISSUE TITLE
Link to "Server Installation Guide" from Wildfly distribution available from web page

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak-documentation#1670]
### Describe the bug

- Assuming I go to https://www.keycloak.org/docs/latest/server_admin/
- Now I click to "Server Installation" in the left top corner (under the list of guides)
- This brings me to old server installation guide, which has lots of references to Wildfly: https://www.keycloak.org/docs/latest/server_installation/

I guess that this link should point to the new guide? Also the old server installation should be probably removed entirely from keycloak/keycloak-documentation?

### Version

19.0.1

**Comment by stianst** [comment]
The server installation guide is now removed from the top corner (see main, not published docs for 19) so closing this one.
