### ISSUE TITLE
No Examples for Spring Boot using SecurityFilterChain

### ISSUE THREAD

**Issue by gudatcomputers** [keycloak/keycloak-documentation#1730]
### Description

Add documentation demonstrating how to integrate Keycloak with Spring Boot using the new `SecurityFilterChain` `@Bean` instead of the deprecated `WebSecurityConfigurerAdapter`

### Motivation

Now that Spring has [deprecated the WebSecurityConfigurerAdapter](https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter) applications using the new preferred architecture have no documented way (as far as I can see) to integrate the newer [SecurityFilterChain](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/web/SecurityFilterChain.html) `@Bean` with keycloak.  Is this supported? 

Thanks for any advice/assistance!

**Comment by stianst** [comment]
The documentation has been moved to [the main Keycloak repository](https://github.com/keycloak/keycloak/tree/main/docs/documentation).

Closing this issue as its been around for a long time without any updates. If still relevant please open a new issue in [the main repository](https://github.com/keycloak/keycloak/issues).
