### ISSUE TITLE
Deadlinks in Javadoc search results

### ISSUE THREAD

**Issue by pReya** [keycloak/keycloak-documentation#1732]
### Describe the bug

When accessing the Javadoc at https://www.keycloak.org/docs-api/20.0.1/javadocs/index.html I came across many 404 deadlinks within a short amount of time.

Happened to me, when I was searching for specific function names in the search box in the upper right corner. E.g. searching for `getGroupsStream()` it seems that all search results are dead links, leading to these urls:

https://www.keycloak.org/docs-api/20.0.1/javadocs/undefined/org/keycloak/models/RealmModel.html#getGroupsStream()
https://www.keycloak.org/docs-api/20.0.1/javadocs/undefined/org/keycloak/models/UserModel.html#getGroupsStream()

Not a JavaDoc expert, but `undefined` inside of the URL doesn't sound good. Probably some kind of misconfiguration?

### Version

20.0.1

### Expected behavior

Search result links should work as expected

**Comment by stianst** [comment]
I'm not able to reproduce this issue. If still relevant please open a new issue in https://github.com/keycloak/keycloak/issues
