### ISSUE TITLE
SSSD documenatation may need to be removed

### ISSUE THREAD

**Issue by Keeper-of-the-Keys** [keycloak/keycloak-documentation#1751]
### Describe the bug

SSSD support seems to be broken and scripts mentioned in the section about it were removed at different stages, so far no devs have replied or weighed in on the subject, unless the feature is going to be restored the documentation should probably be removed.

Even if it is restored in a future version of Keycloak it should not be present in the documentation for the version is which it is not present.

Related bugs/discussions:
https://github.com/keycloak/keycloak/issues/16165
https://github.com/keycloak/keycloak/discussions/15587

Documentation file:
https://github.com/keycloak/keycloak-documentation/blob/main/server_admin/topics/user-federation/sssd.adoc

### Version

20.0.3

### Expected behavior

SSSD support allowing the addition of a FreeIPA realm with 2FA against FreeIPA.

### Actual behavior

SSSD is no longer an option in keycloak.

### How to Reproduce?

Install any recent version of Keycloak and try to do an SSSD based setup as per documentation.

**Comment by Keeper-of-the-Keys** [comment]
Based on the comments in the bug it would seem that SSSD documentation should not be present in keycloak > 17.0.1.

**Comment by Keeper-of-the-Keys** [comment]
Also related https://github.com/keycloak/keycloak/issues/11728

**Comment by stianst** [comment]
Closing this as we're planning to fix the SSSD integration in the new Quarkus distribution soon
